spring:
  application:
    name: Foodics Coding Challenge
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/foodics?reWriteBatchedInserts=true
  jpa:
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    host: smtp.gmail.com
    port: 587
